assets: /tmp/LIBERO/libero/libero/assets
bddl_files: /tmp/LIBERO/libero/libero/bddl_files
benchmark_root: /tmp/LIBERO/libero/libero
datasets: /private/tmp/LIBERO/libero/datasets
init_states: /tmp/LIBERO/libero/libero/init_files
